### ISSUE TITLE
Modal doesn't remove scroll: none; when unmounted

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#108]
If you open a modal and then find a way to navigate away from it without closing it, the scrollbar doesn't reappear.

This appears to be an easy fix: we need to run cleanup on `componentWillUnmount`, but it's currently only being run [in the `onClose` method](https://github.com/wwnorton/design-system/blob/16ddb6e5cc158f2594b44adcebfe062e3453305a/packages/react/src/components/Modal/index.tsx#L290).

**Comment by Apatil15** [comment]
Modal - > index.tsx - > onOpen -> line number 276 comment out  fixing this problem

**Comment by sh0ji** [comment]
A strict requirement of all modal dialogs is that you cannot interact with anything except the dialog when it is open. That includes scrolling, so the body needs to be `overflow: hidden` when the modal is open. The issue is that the `overflow: hidden` isn't being cleaned up properly when the component unmounts.

**Comment by Apatil15** [comment]
Added code on componentWillUnmount same as onClose method for body.style.overflow. unit tested various scenarios.

**Comment by sh0ji** [comment]
Closed by ec8d19779f184688f76895e816d1244955faae9f.
