### ISSUE TITLE
Decoupling components [NDS-31] [NDS-32] [NDS-33] [NDS-34]

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#111]
Some of our current components are what many design systems call "Patterns"&mdash;a single interface that composes together multiple components. This is very helpful for the more opinionated patterns that we want to promote, such as using a Text Field to ensure that the field always has a label and accessible feedback.

But since the internals of some of these patterns aren't first-class components of the design system, it's impossible for users to compose their own patterns with them. To better facilitate those use cases, I would like to start thinking about decoupling some of our components.

## Existing Composite Components

The following components compose anatomy/functionality together in a way that doesn't make some part of the internals accessible without using the component. For instance, it's not possible to use a dropdown's listbox without using the dropdown.

* `TextField` - label+description, an input, and field feedback that contains errors and a counter.
   * [NDS-31] 
* `Dropdown` - `Button`, a label, a listbox, and popover functionality.
   * [NDS-32]
* `Modal` - `Button` (the "close" `IconButton`), a "header," an "action bar."
   * [NDS-33]
* `Switch` - `Button`, label+description, and `Tooltip` (when `tipped`, the label displays as a tooltip)
   * [NDS-34]

[NDS-31]: https://wwnorton.atlassian.net/browse/NDS-31
[NDS-32]: https://wwnorton.atlassian.net/browse/NDS-32
[NDS-33]: https://wwnorton.atlassian.net/browse/NDS-33
[NDS-34]: https://wwnorton.atlassian.net/browse/NDS-34

**Comment by dmedjordan** [comment]
Issue linked to JIRA Stories: [NDS-31] [NDS-32] [NDS-33] [NDS-34]
