### ISSUE TITLE
Textfield cursor behaving strangely when editing

### ISSUE THREAD

**Issue by dnvargas25** [wwnorton/design-system#13]
In the Storybook, the Text Field component allows a user to add and edit text. When editing this text, if the cursor is placed anywhere except after the last character, it only allows for a single action (deleting one character or adding one character) before the cursor is automatically moved back to the end of the string of text. This occurs in each example of the "Text Field" Component on Safari (Mac), Chrome (Windows, Mac), Firefox (Windows, Mac), and Edge (Windows).

**Comment by sh0ji** [comment]
Closed by #22.
