### ISSUE TITLE
Correction: Purple-70

### ISSUE THREAD

**Issue by btri-wwn** [wwnorton/design-system#131]
Discovered a discrepancy with **purple-70.**

HEX code should = **#5D4DAB**
This color has a contrast ratio of **6.74**, which is more in-line with the other grade-70 swatches.

**Comment by sh0ji** [comment]
@Apatil15, this should be straightforward and I think this can be bundled with #104. Would you mind opening a PR for these changes?

**Comment by Apatil15** [comment]
@sh0ji This issue has been fixed and push to branch "issues"
