### ISSUE TITLE
Component: Tag [NDS-35]

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#135]
> A tag is an interactive label that contains text or numbers to communicate status or classification. It may or may not be dismissible.

(split from #41)

## Anatomy

A tag includes:
1. A container
1. A label
1. An icon (optional)
1. A dismiss button (optional)
1. A link (optional)

## Reference

- Shopify: https://polaris.shopify.com/components/forms/tag
- Salesforce (Pills): https://www.lightningdesignsystem.com/components/pills/, https://react.lightningdesignsystem.com/components/pill-container/
- Atlassian: https://atlassian.design/components/lozenge/examples

[NDS-35]

[NDS-35]: https://wwnorton.atlassian.net/browse/NDS-35

**Comment by Apatil15** [comment]
@sh0ji  I created props for tag component please review and suggest, also I have compared other components common props

Tag Props

| Props | Type | Description | Default |
| :---     |  :---     |   :---   | :---   |
| close   |  boolean | Remove/hide tag | No close icon
| icon   |  icon variant | Display icon before or after tag | No icon
| disabled   | boolean | Disabled tag | false
| color   |  color variant | Text and close icon color | nds-text-color
| bgcolor   |  color variant | Background color | nds-gray-20
| link   |  ? | Redirect to route | ?


Other components same props
| Props | Shopify | Ant | Atlassian | 
|     :---   |     :---      |          :--- |         :--- | 
| close   | onRemove     | closable   | isRemovable | Remove/hide tag 
| icon   |  no icon       | icon      | elemBefore | Show icon before or after tag text
| disabled   |disabled      | no disable      | no disable | Disabled tag
| color   | no color      | color     | color | background color 
| link | onClick  | Using child anchor element | href

**Comment by dmedjordan** [comment]
Issue linked to JIRA Story: NDS-35
