### ISSUE TITLE
Update email regex [NDS-18]

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#152]
After adding a CodeQL workflow (453751043688e3421d3a4f9f1c3318d81b6b893b), our security check has [flagged the email regex as inefficient](https://github.com/wwnorton/design-system/security/code-scanning/1?query=ref%3Arefs%2Fheads%2Fmain). Let's figure out an alternative.

[NDS-18]

[NDS-18]: https://wwnorton.atlassian.net/browse/NDS-18

**Comment by dmedjordan** [comment]
Issue linked to JIRA Story: [NDS-18]
