### ISSUE TITLE
IconButton tooltips overlapping

### ISSUE THREAD

**Issue by cafrias** [wwnorton/design-system#2]
Hey there! I have the current issue with `IconButton` components:

![controls-tooltip](https://user-images.githubusercontent.com/16751797/89568094-2cff9f80-d7f9-11ea-8e77-40ffa118b60a.gif)

As you can see the tooltips are overlapping with the other buttons on the side panel. On a smaller breakpoint this is not a problem since this sidebar goes to the top:

![controls-tooltip-sm](https://user-images.githubusercontent.com/16751797/89568282-764fef00-d7f9-11ea-8c95-48bfd0e63fbe.gif)

One suggestion would be to be able to tell the direction where the tooltip opens to, in this scenario opening to the right would be just fine.

**Comment by sh0ji** [comment]
I implemented a fix for this in #4. All components that can use tooltips now expose a `tooltipProps` prop that you can use to set a subset of the tooltip's props.

To fix the vertical toolbar issue, you should be able to do this:

```jsx
<IconButton tooltipProps={{ placement: 'right' }} />
```
And you can also modify the `hideDelay` to reduce the length of time before the tooltips disappear. This defaults to `200` (ms) now to ensure that users can select the contents of the tooltip.
