### ISSUE TITLE
Update to eslint-config-norton v4

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#26]
The latest 4.0 beta of [eslint-config-norton](https://github.com/wwnorton/style/tree/main/packages/eslint-config-norton) has some breaking changes in it that will require some effort to update in the design system, which is why I opted not to update it for the first release candidate. Let's start that work. Some notes:

- We're currently using nested `.eslintrc` files to apply different rules to different packages via [the eslint configuration cascade](https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy). These should probably be removed since the new config targets file globs to determine which rules to apply (it uses overrides), allowing us to use one root config.
- ~~We'll want to enforce [no default exports, which is in `eslint-config-norton@4.0.0-beta.0`](https://github.com/wwnorton/style/blob/v4.0.0-beta.0/src/rules/bestPractices.js) but not in subsequent versions. I opened [an issue about this in the style repo](https://github.com/wwnorton/style/issues/70)~~.
- There will be new type errors since we're not currently using [the recommended-requiring-type-checking](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/TYPED_LINTING.md). Some of these type errors might require real refactoring or point to actual issues. We'll tackle those on a case-by-case basis.

**Comment by ParmeJon** [comment]
I have the norton config set up locally. I kept some of the individual rules for `docs` and `packages/react`. Currently, looking at 336 errors and 77 warnings after an initial `npm run lint:es-fix`. Will be working on the [eslint-config-norton-v4-upgrade branch](https://github.com/wwnorton/design-system/tree/eslint-config-norton-v4-upgrade).

**Comment by sh0ji** [comment]
I updated our config to capture our rules in lieu of eslint-config-norton in ec91f9b04d6bc14f543fdccc27a0bf0dfd733360. We'll revisit this when eslint-config-norton comes out of beta.
