### ISSUE TITLE
Loading/Progress Component

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#27]
We need a component that can be used to indicate both determinate and indeterminate loading states. We need two visual designs/animations for this (circle and bar), as well as a determinate and indeterminate variant for each, totalling 4 designs.

Here are rough guidelines and examples for each.

* Indeterminate circle* - used for single components when progress is unknown, such as during an asynchronous request.
  - Example: a "save" button that saves a student's progress on an assignment might display this after clicking it but before the server has responded (before it's saved).
* Determinate circle - used to convey progress for single components when an estimated time to completion can be known.
  - Example: a "view offline" or "download" button/checkbox that offlines an ebook might use one of these to show progress adjacent to the chapter title that is currently being downloaded.
* Indeterminate bar - used for whole-page loading when progress is unknown.
  - Example: this might appear at the top of the page after opening a new page but before the entire page is done loading.
* Determinate bar - used to display progress for a larger component or page when progress is known.
  - Example: this could appear in an ebook to convey the current position in the book.

\* The indeterminate circle is our most used and therefore the most important right now.

## References

* Visual design: [Zeplin loading](https://zpl.io/2yAeWOJ)
* Material Design's [Progress indicators](https://material.io/components/progress-indicators)

**Comment by sh0ji** [comment]
This requires more research and design before being ready for development. Our priority is the **indeterminate circle** but we need a system that works for all four permutations. Let's collect/come up with some ideas here.

**Comment by btri-wwn** [comment]
I've updated the **Spinner** components on Zeplin.
This update adds labels to spinner

**Comment by sh0ji** [comment]
For posterity: the root (private) component is the `BaseProgressIndicator`, which thinly wraps [Material UI's `CircularProgress`](https://material-ui.com/api/circular-progress/) for the time being. This allows us to remove the Material UI dependency at some point in the future. Our only public API for this right now is the `Spinner` component.
