### ISSUE TITLE
Modal title style with forced margins

### ISSUE THREAD

**Issue by cafrias** [wwnorton/design-system#271]
**Describe the bug**
Modal styles for the title are display with big top and bottom margins for the H2 element used to contain the title.

The problem is that the styles for h2 tag from `main.css` coming from the design system, contains a couple of `!important`:

``` main.css
h2 {
  margin-top: 0;
  margin-bottom: 1rem;
  margin-bottom: var(--nds-spacing-4);
  font-style: var(--nds-font-style-headings);
  font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell,
    Noto Sans, sans-serif, Segoe UI, Roboto, Helvetica Neue, arial, Noto Sans,
    Liberation Sans, sans-serif, Apple Color Emoji, Segoe UI Emoji,
    Segoe UI Symbol, Noto Color Emoji;
  font-family: var(--nds-font-family-headings);
  font-size: 1.5rem;
  font-size: var(--nds-font-size-h2);
  font-weight: 700;
  font-weight: var(--nds-font-weight-headings);
  line-height: 1.125;
  line-height: var(--nds-line-height-2);
  margin-top: 2.5rem !important;
  margin-top: var(--nds-spacing-10) !important;
  margin-bottom: 1.25rem !important;
  margin-bottom: var(--nds-spacing-5) !important;
}
```

**To Reproduce**
1. Create a modal
2. Add a title to the modal

**Expected behavior**
It's expected not to show the margins.

**Screenshots**
![broken](https://user-images.githubusercontent.com/16751797/161619269-bc62ff8d-d19e-45d7-854b-f7140cdda346.PNG)

**Desktop:**

- OS: Windows 10
- Browser Chrome 
- Version 99.0.4844.84

**Comment by JRebella** [comment]
Hey @cafrias thanks for the issue report!

This was already fixed on https://github.com/wwnorton/design-system/pull/256 but hasn't been released yet. Should be included in the next release
