### ISSUE TITLE
Component: Badge [NDS-3]

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#41]
> A badge is an indicator communicating a state, update or count for the component or item it is describing. It cannot be dismissed or interacted with.

Our badge component is a simple content component (in other words, it is non-interactive).

## Anatomy

A badge includes:
- A container 
- A label (required but will be hidden in dot badge state)
- An icon (optional)

## Reference

- Open UI: https://github.com/WICG/open-ui/pull/224
- Ant design: https://ant.design/components/badge/#components-badge-demo-ribbbon
- Shopify: https://polaris.shopify.com/components/images-and-icons/badge
- Lightning: https://www.lightningdesignsystem.com/components/badges/

## Old description (for posterity)

We have a need for a component that can be used to label or tag small bits of information. There are effectively two variants of this component: a non-interactive one, and an interactive one. It appears in a lot of design systems under the names "badge," "chip," "label," and "tag."

- [Material Chips](https://material.io/components/chips) - interactive
- [Ant Design Tag](https://ant.design/components/tag/) - non-interactive (the `CheckableTag` variant is interactive)
- [USWDS Tag](https://designsystem.digital.gov/components/tag/) - non-interactive
- [Lightning Badge](https://www.lightningdesignsystem.com/components/badges/) - non-interactive
- [Atlassian DS Badge](https://atlassian.design/components/badge) - non-interactive
- [Atlassian DS Tab](https://atlassian.design/components/tag) - interactive
- [Carbon Tag](https://www.carbondesignsystem.com/components/tag) - hybrid (adding the `filter` prop makes it interactive)
- [GitHub Label](https://primer.style/components/Label) - non-interactive

[NDS-3]

[NDS-3]: https://wwnorton.atlassian.net/browse/NDS-3

**Comment by sh0ji** [comment]
Splitting this into two components: Badge (this issue) and Tag (#135).

**Comment by dmedjordan** [comment]
Issue linked to JIRA Story: [NDS-3]
