### ISSUE TITLE
Button Component Updates [NDS-9] [NDS-29]

### ISSUE THREAD

**Issue by btri-wwn** [wwnorton/design-system#52]
I've updated the Button component on Zeplin. 

The changes have to do with disabled and loading states.
- Use the new single-color spinner component in the loading state.
   - [NDS-9]
- Please disable the cursor when hovering over disabled and loading state buttons. 
   - [NDS-29]

[NDS-9]: https://wwnorton.atlassian.net/browse/NDS-9

[NDS-29]: https://wwnorton.atlassian.net/browse/NDS-29

**Comment by sh0ji** [comment]
By "disable the cursor," do you mean [cursor: not-allowed](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)?

**Comment by dmedjordan** [comment]
Issue linked to JIRA Stories: [NDS-9] [NDS-29]
