### ISSUE TITLE
Color Schemes [NDS-28]

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#57]
We need to finalize our color schemes and then document how they work and how to use them.

## Context

Our current color system uses [role tokens](https://wwnorton.github.io/design-system/docs/color#role-tokens) to capture color usage across an application. This is designed to allow for easy customization of color across the system and the components and is a core part of our theming system along with customizable role-based tokens for our other subsystems like typography.

We're currently shipping two color schemes: a [light scheme](https://github.com/wwnorton/design-system/blob/68bfc7601271aa00fe940e858f54ff592a778717/packages/core/src/color/tokens.scss#L211-L229) and a [dark scheme](https://github.com/wwnorton/design-system/blob/main/packages/core/src/color/tokens.scss#L233-L241). The light scheme was defined by @btri-wwn and the dark scheme was defined by me for the website's "dark mode" toggle. The dark scheme is disabled by default, allowing applications to opt into it via [the `$enable-dark-scheme`](https://github.com/wwnorton/design-system/blob/68bfc7601271aa00fe940e858f54ff592a778717/packages/core/src/_config.scss#L21-L25) Sass configuration variable.

We also ship an undocumented [`useColorScheme` React hook](https://github.com/wwnorton/design-system/blob/b300c821c508d3a7dfd5726fbcf6edaf0735bf32/packages/react/src/hooks/useColorScheme.ts) that helps React applications tie color schemes to user actions or preferences. The "Dark mode toggle" on the top navbar of our documentation [uses this hook to control the color scheme context](https://github.com/wwnorton/design-system/blob/68bfc7601271aa00fe940e858f54ff592a778717/website/src/theme/Navbar/index.tsx#L54).

## Naming

A note on the naming: I've been calling a palette of defined color role tokens a "color scheme" because CSS has standardized around that name (as seen in [the `prefers-color-scheme` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)). It also avoids the word "theme," which I would prefer to use for the entire token set, not just color.

[NDS-28]

[NDS-28]: https://wwnorton.atlassian.net/browse/NDS-28

**Comment by dmedjordan** [comment]
Issue linked to JIRA Story: [NDS-28]
