### ISSUE TITLE
Icons Update

### ISSUE THREAD

**Issue by btri-wwn** [wwnorton/design-system#65]
Icons board updated on Zeplin. 
Please add the following icons:

- warning
- star
- star-border

(removed large chevron icons)

**Comment by sh0ji** [comment]
Oh you know what, we already have [star](https://material.io/resources/icons/?icon=star&style=baseline) and [star-outline](https://material.io/resources/icons/?icon=star_outline&style=baseline) (they're enumerated in the [default Icon story](https://wwnorton.github.io/design-system/storybook/?path=/story/icon--default)'s "Icon" knob and can also all be seen on the [all icons story](https://wwnorton.github.io/design-system/storybook/?path=/story/icon--all-icons)).

And it looks like @ParmeJon has implemented [warning](https://material.io/resources/icons/?icon=warning&style=baseline) as [part of the Callout PR](https://github.com/wwnorton/design-system/pull/69/files?file-filters%5B%5D=.scss&file-filters%5B%5D=.ts#diff-4a22c57213cf34ae577646d6ee03795418b1893fa6e125fa5ae04f360d370c7eR332-R337).

I'll keep this open but we can close it when #69 lands.
