### ISSUE TITLE
React: revisiting class naming [NDS-27]

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#67]
I'd like to consider revisiting and refactoring how we're handling React class naming to simplify things a bit.

Specifically, I'd like to start by hard-coding the default classes for className props. This would include actual `className` defaults if they exist, but also subordinate [BEM](http://getbem.com/)-based class names. This will sacrifice className composition for more readable code (i.e., `nds-button--solid` vs. `${prefix('button')}--variant`). That feels worthwhile to me.

@Apatil15, @ParmeJon: do you two have any concerns with this? Could this potentially break any current known uses of the design system? If so, is there a way for us to do it in a non-breaking way?

## Current Conventions

Many of our current conventions would need to be changed to accomplish this. For instance, we currently use [a prefix function](https://github.com/wwnorton/design-system/blob/e0511cc644bdb7215fec77305c1a8f8feb7d0168/packages/react/src/config.ts#L31-L35) to set the `baseName` in our components, which forms the "block" of our BEM classes. That could effectively be removed.

Other conventions are best demonstrated in a real component so let's take a look at how this works and how classes are formed in Button:

* `baseName` is soft-coded as `prefix('button')`, which evaluates to `nds-button` when the design system is configured to use the "nds" namespace (this is the default namespace).
https://github.com/wwnorton/design-system/blob/e0511cc644bdb7215fec77305c1a8f8feb7d0168/packages/react/src/components/Button/Button.tsx#L60
* That `baseName` is then included in the button's `className` (via the [classnames](https://github.com/JedWatson/classnames) utility).
https://github.com/wwnorton/design-system/blob/e0511cc644bdb7215fec77305c1a8f8feb7d0168/packages/react/src/components/Button/Button.tsx#L99-L117
* Note that whatever `className` the user provides is **also** included in the rendered class. If they want to omit the `baseName`, they have to set it to an empty string. This feels kind of awkward to me. In other words:
```jsx
<Button className="my-button"> → <button class="nds-button my-button">
<Button baseName="" className="my-button"> → <button class="my-button">
```
* Subordinate elements use `baseName` to construct their `className` following the `block__element` BEM convention.
https://github.com/wwnorton/design-system/blob/e0511cc644bdb7215fec77305c1a8f8feb7d0168/packages/react/src/components/Button/Button.tsx#L67-L68
* Variants use the `baseName` to construct a modifier `className` following the `block--modifier` BEM convention.
https://github.com/wwnorton/design-system/blob/e0511cc644bdb7215fec77305c1a8f8feb7d0168/packages/react/src/components/Button/Button.tsx#L101-L105

[NDS-27]

[NDS-27]: https://wwnorton.atlassian.net/browse/NDS-27

**Comment by Apatil15** [comment]
@sh0ji This is good idea to override the base class,  we implemented baseName = prefix('button'), just needs to add extra condition to check base="". No concern from my end 
@ParmeJon

**Comment by ParmeJon** [comment]
I agree that it is a bit awkward to have to set `baseName="" ` in order to omit baseName in the className as a developer. I don't have any concerns that stick out to me immediately. We would just have to replace all the `${baseName}` with the hard coded values? 

Does this mean if a developer writes a value for `className` it will override our default `nds-button` now that we are thinking of getting rid of the baseName api? Or am I misunderstanding?

example:
```
// Before - nds-button is set to className internally
<Button className="my-button"> → <button class="nds-button my-button">

// After - our className value overrides className internals
<Button className="my-button"> → <button class="my-button">
```

I do feel like when I was originally developing Helpdesk with NDS I didn't really know how to turn off the default `nds-button` className at first and it seemed weird that it would be there even though I explicitly set className to something I wanted. Figured out it was just how it was built later on though.

**Comment by sh0ji** [comment]
> Does this mean if a developer writes a value for `className` it will override our default `nds-button` now that we are thinking of getting rid of the baseName api? Or am I misunderstanding?

You're not really misunderstanding&mdash;I just didn't really specify which direction we should go for this particular point, just that it's awkward. I'd like to make the change but worry that it would be breaking for anyone who wrote code that expects `nds-button` to always exist (for instance).

There's also the question of how we handle modifiers if we made that change. For instance, the `color` prop on our `Button` currently sets the color as a BEM modifier (`${baseName}--${color}`).

```jsx
// this would be clear:
<Button className="my-button"> → <button class="my-button">

// but what do you expect here?
<Button className="my-button" color="red">

// a) the user's className overrides everything
<button class="my-button">

// b) modifiers are still applied using the default className
<button class="my-button nds-button--red">

// c) modifiers are applied using the user-specified className
<button class="my-button my-button--red">

// d) we just drop the modifier convention and use data-attributes for internal styling
<button class="my-button" data-color="red">
```

**Comment by dmedjordan** [comment]
Issue linked to JIRA Story: [NDS-27]
