### ISSUE TITLE
Combobox component [NDS-44]

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#78]
We need a [combobox](https://w3c.github.io/aria/#combobox) that allows the user to begin typing and then select an option from a list. While a combobox describes a generic pattern that could potentially be used for things like a date picker, this component should narrowly allow for text input and dropdown selection.

## Anatomy

* Text field - the [input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) field where the user can type. This should have the same anatomy as our [Text Field](https://wwnorton.github.io/design-system/docs/components/text-field).
* Dropdown list box - a [listbox](https://w3c.github.io/aria/#listbox) that populates its contents based on user input in the text field.
   - Note: our [BaseListbox](https://github.com/wwnorton/design-system/blob/main/packages/react/src/components/BaseListbox/index.tsx) accomplishes this.

## References

Our first priority should be mimicking or using existing standards.

- [MDN - `<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) - the native HTML way to do this is to associate an `<input>` with a `<datalist>`. Relevant attributes:
   - [`list`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdeflist) - refers to the `id` of the `<datalist>`.
   - [`autocomplete`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values) - defines how autocomplete should work.
- [ARIA Authoring Practices - Combobox](https://w3c.github.io/aria-practices/#combobox) - how to do the same thing with `<input>` + `<ul role="listbox">`. Note that there are six examples documented, but the non-editable ones and the non-listbox ones (grid & datepicker) are out of scope.
   - [List and inline autocomplete](https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-both.html)
   - [Only list autocomplete](https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-list.html)
   - [No autocomplete](https://w3c.github.io/aria-practices/examples/combobox/combobox-autocomplete-none.html)

Our second priority should be to look at how other design systems implement this pattern and finding commonality.

- [Lightning - Combobox](https://www.lightningdesignsystem.com/components/combobox/)
- [Atlassian - Select](https://atlassian.design/components/select/examples)
- [Ant Design - Select](https://ant.design/components/select/)
- [Bold - Select](https://bold.bridge.ufsc.br/en/components/select/)

[NDS-44]

[NDS-44]: https://wwnorton.atlassian.net/browse/NDS-44

**Comment by dmedjordan** [comment]
Issue linked to JIRA Story: [NDS-44]
