### ISSUE TITLE
Callout Component: VQA/Edit

### ISSUE THREAD

**Issue by btri-wwn** [wwnorton/design-system#81]
Callout looks good, however I'd like to request the following adjustments (now up on Zeplin).

- **Padding:**  32px --> 24px
- **Icon size:**  24px --> 20px
- **Title:** heading-5 --> heading-4

The overall effect is to make the callout smaller. After trying it out in projects in a UI context, i think the current size feels big. However, the current size does work if placed in articles/long-form text. 

Lmk thoughts.

**Comment by sh0ji** [comment]
Yeah, that makes sense to me. I had a similar thought that it was quite big when I used it in the documentation. I believe the current title is effectively using the `heading-4` typeset, which uses `line-height: var(--nds-line-height-heading)` (that equals `1.25`) and `font-size: var(--nds-font-size-18)`. Did you want to change one of those to make it smaller?

@ParmeJon, could make these changes in a new PR? It's effectively these changes:

```scss
$padding-x: spacing.spacer('callout-x') !default; // switch to the spacing-6 token
$padding-y: spacing.spacer('callout-y') !default; // switch to the spacing-6 token
$icon-size: 1.25rem !default; // was 1.5rem
```

And then update the title too.

**Comment by ParmeJon** [comment]
I also noticed, that the dismiss button actually moves down a bit when `border: top`. I'll look into that as well.

**Comment by sh0ji** [comment]
> After changing the icon sizing, it's centering in regards to the title seems a bit lower.
> <img alt="Screen Shot 2021-02-12 at 3 22 13 PM" width="449" src="https://user-images.githubusercontent.com/41137981/107818846-3472a900-6d46-11eb-90f7-2ba2877b021b.png">
> 
> I also noticed, that the dismiss button actually moves down a bit when `border: top` and if the title exists.
> <img alt="Screen Shot 2021-02-12 at 3 22 25 PM" width="446" src="https://user-images.githubusercontent.com/41137981/107818869-3b012080-6d46-11eb-97fb-d526f428a1e3.png">
> 
> I'll look into these as well.

Would you mind opening a new PR to address these two issues? Both can be `refactor` commits since you won't be addressing anything that's been released.

**Comment by ParmeJon** [comment]
https://github.com/wwnorton/design-system/pull/85 
Made some adjustments here for those two issues. @sh0ji
