### ISSUE TITLE
React Styling [NDS-23] [NDS-24] [NDS-25] [NDS-26]

### ISSUE THREAD

**Issue by sh0ji** [wwnorton/design-system#93]
For our initial release, we decided to go with the most widely-supported form of styling for our components, separating stylesheets from component structure and logic. In other words, `@wwnds/core` handles styling, while `@wwnds/react` handles content structure and interaction design. This helps us immensely for projects that don't use React but results in an less enjoyable React developer experience.

I'd like to reassess that approach and provide a better developer experience for React users.

## Current styling issues

Here are the problems that I've identified that we'll want to solve:

- `@wwnds/react` has no styling without `@wwnds/core`. While the React components technically work without any styling, they only really work for screen reader users. Everyone else needs the visual styling to make sense of them.
   - I can't imagine a solution to this that wouldn't be a breaking change. If I'm right about that, this whole issue should be a `v2` issue.  
   - [NDS-23]
- Overriding the component `className` doesn't do what you'd expect. Explained in #67.
   - This also feels breaking to me.  
   - [NDS-24]
- Component styles don't work without global styles. Component styles use CSS custom properties defined on the `:root`, which means you have to `@include` the root styles (`@include tokens`) once in a global stylesheet. This doesn't appeal to anyone who expects components to be strictly isolated and fully standalone.
   - There is likely a way to change this in a non-breaking way, but I'm inclined to just bundle this with `v2` for simplicity.  
   - [NDS-25]
- Our `:root` styles include tokens that aren't used by any component or utility. The best example of this is our color system, which includes 10 CSS custom properties per family.
   - CSS bloat is the main concern but what's the _actual_ performance impact in the real world? It'd be good to do some analysis on this before deciding what needs to change.  
   - [NDS-26]

## Requirements

The following are requirements that we still need to meet, regardless of the solution.

- It must still be possible to use both global and component styling without having to use React. Our ebooks need simple stylesheets because they do not use React.
- The implementation must reflect our [foundations](https://wwnorton.github.io/design-system/docs/foundations). Conceptual note: the code _is not_ the design system. It's just an implementation of it.
- It must still be possible to opt out of or override styles at the component and anatomy level.

[NDS-23]: https://wwnorton.atlassian.net/browse/NDS-23
[NDS-24]: https://wwnorton.atlassian.net/browse/NDS-24
[NDS-25]: https://wwnorton.atlassian.net/browse/NDS-25
[NDS-26]: https://wwnorton.atlassian.net/browse/NDS-26

**Comment by dmedjordan** [comment]
Issue linked to JIRA Stories: [NDS-23] [NDS-24] [NDS-25] [NDS-26]

**Comment by dmedjordan** [comment]
Issue linked to JIRA Stories: NDS-23 NDS-24 NDS-25 NDS-26
